# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: "Africa/Cairo"

# jekyll-seo-tag settings
title: Cookie
tagline: "Hello I'm Habiba, We INNOVATE Bootcamp | DEPI | CyberTalents Bootcamp | eJPTv1 Prep | Google Cybersecurity by Coursera | Security+ SY0-601"
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname
url: "https://cookies307.github.io"

github:
  username: Cookies307

social:
  name: Habiba Muhammed
  email: habebamohamed307@gmail.com
  links:
    - https://github.com/Cookies307

# Site Verification Settings
webmaster_verifications: {}

# Web Analytics Settings
analytics: {}

# Page views settings
pageviews:
  provider:

# Prefer color scheme
theme_mode: dark

# The CDN endpoint
cdn:

# the avatar on sidebar
avatar: "/assets/images/WhatsApp Image 2025-08-07 at 09.05.48_bfb81fee.jpg"

# Site-wide social preview image
social_preview_image:

# Global switch for TOC
toc: true

comments:
  provider:

# Self-hosted static assets
assets:
  self_host:
    enabled: false

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  posts:
    output: true
    permalink: /posts/:title/
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/