# The Site Configuration
theme: jekyll-theme-chirpy
lang: en
timezone: "Africa/Cairo"
title: Cookies
tagline: "Hello I'm Habiba, We INNOVATE Bootcamp | DEPI | CyberTalents Bootcamp | eJPTv1 Prep | Google Cybersecurity by Coursera | Security+ SY0-601"
description: >- A minimal, responsive and feature-rich Jekyll theme for technical writing.
url: "https://cookies307.github.io"
github:
  username: Cookies307
social:
  name: Habiba Muhammed
  email: habebamohamed307@gmail.com
  links:
    - https://github.com/Cookies307
avatar: "/assets/images/WhatsApp Image 2025-08-07 at 09.05.48_bfb81fee.jpg"
toc: true
collections:
  posts:
    output: true
    permalink: /posts/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
paginate: 10
baseurl: ""
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
sass:
  style: compressed
compress_html:
  clippings: all
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag